version: "3"

services: 
  postgres-labelizer:
    image: postgres:alpine
    container_name: labelizer_postgres_database
    ports:
      - 54321:5432
    environment: 
      - POSTGRES_DB=data_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-labelizer-data:/var/lib/postgresql/data/
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres-labelizer-data:
